# Generated by Django 5.2.16 on 2026-08-20 18:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم العميلة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات وتفضيلات')),
                ('allergy_info', models.TextField(blank=True, default='', verbose_name='الحساسية والمحاذير الطبية')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='إجمالي الزيارات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي الإنفاق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميلة',
                'verbose_name_plural': 'العميلات',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج / المادة')),
                ('sku', models.CharField(blank=True, default='', max_length=100, verbose_name='رمز الصنف (SKU)')),
                ('item_type', models.CharField(choices=[('retail', 'منتج بيع تجزئة'), ('backbar_consumable', 'مستهلكات داخلية بالجرام/المل')], default='backbar_consumable', max_length=50, verbose_name='نوع الصنف')),
                ('unit', models.CharField(choices=[('unit', 'قطعة / علبة'), ('gram', 'جرام (g)'), ('ml', 'مليلتر (ml)')], default='gram', max_length=20, verbose_name='وحدة القياس')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المخزون الحالي')),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12, verbose_name='حد التنبيه')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر التكلفة')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر البيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صنف مخزون',
                'verbose_name_plural': 'أصناف المخزون',
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصالون')),
                ('subdomain', models.SlugField(max_length=100, unique=True, verbose_name='النطاق الفرعي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('tax_number', models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='نسبة العربون %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صالون',
                'verbose_name_plural': 'الصالونات',
                'db_table': 'salons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('status', models.CharField(choices=[('pending_deposit', 'بانتظار دفع العربون'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'عدم حضور')], default='confirmed', max_length=50, verbose_name='حالة الموعد')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='العربون المدفوع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي القيمة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.client')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'db_table': 'appointments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClientHairFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula_text', models.TextField(verbose_name='تركيبة الصبغة / المعالجة بالتفصيل')),
                ('brand_name', models.CharField(blank=True, default='', max_length=100, verbose_name='الماركة التجارية')),
                ('before_photo_url', models.URLField(blank=True, default='', verbose_name='صورة قبل')),
                ('after_photo_url', models.URLField(blank=True, default='', verbose_name='صورة بعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hair_formulas', to='salons.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_formulas', to='salons.client')),
            ],
            options={
                'verbose_name': 'تركيبة شعر',
                'verbose_name_plural': 'أرشيف تركيبات الشعر',
                'db_table': 'client_hair_formulas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المستهلكة')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_usages', to='salons.appointment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='salons.inventoryitem')),
            ],
            options={
                'verbose_name': 'استهلاك مادة',
                'verbose_name_plural': 'سجل استهلاك المواد',
                'db_table': 'inventory_usages',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='client',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='salons.salon'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('category', models.CharField(choices=[('hair', 'العناية بالشعر والصبغات'), ('nails', 'الأظافر والمانيكير'), ('skin', 'البشرة والعناية'), ('spa', 'المساج والاسترخاء'), ('makeup', 'المكياج والمناسبات')], default='hair', max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, default='', verbose_name='وصف الخدمة')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='مدة الخدمة (بالدقائق)')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=10, verbose_name='وقت التعقيم والتجهيز (بالدقائق)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (شامل الضريبة)')),
                ('requires_chair_type', models.CharField(choices=[('styling', 'كرسي التصفيف والقص'), ('washing', 'كرسي الغسيل والمعالجة'), ('spa', 'غرفة السبا والعناية'), ('general', 'كرسي عام')], default='styling', max_length=50, verbose_name='نوع الكرسي المطلوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'db_table': 'services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.service'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الجوال')),
                ('role', models.CharField(choices=[('owner', 'مالك / مدير'), ('receptionist', 'موظفة استقبال'), ('stylist', 'مصففة / أخصائية'), ('assistant', 'مساعدة')], default='stylist', max_length=50, verbose_name='الدور الوظيفي')),
                ('specialty', models.CharField(blank=True, default='تصفيف وصبغات', max_length=150, verbose_name='التخصص')),
                ('commission_rate_services', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='عمولة الخدمات %')),
                ('commission_rate_retail', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='عمولة مبيعات التجزئة %')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='صورة الموظفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salons.salon')),
            ],
            options={
                'verbose_name': 'موظفة',
                'verbose_name_plural': 'الموظفات',
                'db_table': 'staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع قبل الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مبلغ الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصم')),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإكرامية')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع الصافي')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة ائتمان'), ('mada', 'مدى'), ('apple_pay', 'Apple Pay'), ('split', 'دفع مجزأ')], default='mada', max_length=50, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوعة'), ('pending', 'معلقة'), ('refunded', 'مسترجعة')], default='paid', max_length=50, verbose_name='حالة الدفع')),
                ('staff_commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='عمولة الموظفة المحسوبة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='salons.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='salons.client')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='salons.salon')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='salons.staff')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salons.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('salon', 'phone')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['salon', 'start_time'], name='appointment_salon_i_fd8c83_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'start_time'], name='appointment_staff_i_50533a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
    ]
