# Generated by Django 5.2.16 on 2026-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='staff',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='كلمة المرور المشفرة'),
        ),
        migrations.AddField(
            model_name='staff',
            name='pin_code',
            field=models.CharField(blank=True, default='1234', max_length=10, verbose_name='رمز PIN السريع'),
        ),
    ]
